name: GitHub Actions Demo

on:
  push:
    branches:
      - feature/django-github-action

env:
  ENVIRONMENT: test
  MIN_COVERAGE: 200

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Unit Tests
      id: run-unittest
      run: |
        docker-compose -f docker-compose.test.yaml up --build
    - name: After testing
      if: steps.run-unittest.outcome.exit_code == 0
      run: |
        echo 'Faield test'
