name: GitHub Actions Demo

on:
  push:
    branches:
      - feature/django-github-action

env:
  ENVIRONMENT: test
  MIN_COVERAGE: 200

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    # - name: Run Tests
    #   id: run-unittest
    #   run: |
    #     docker-compose -f docker-compose.test.yaml up --build
    - name: Run Tests
      uses: actions/django-github-action@v1
      run: docker-compose -f docker-compose.test.yaml up --build
    - name: After testing
      if: steps.run-unittest.outcome.exit_code == 0
      run: |
        echo 'Faield test'
