name: GitHub Actions Demo

on:
  push:
    branches: [ django-github-action ]

env:
  ENVIRONMENT: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Run Tests
      run: |
        docker-compose -f docker-compose.test.yml up --build
